version: "3.11"

services:
  postgres:
    container_name: flpostgres
    hostname: flpostgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_USER:-videoteka}
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: flask_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  flask_app:
    container_name: flask_app
    image: flast_app/films_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    env_file:
      .docker_env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
    entrypoint: >
      bash -c "flask db upgrade
      && flask db migrate
      && flask db upgrade
      && flask seed"



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  flask_app_migrate: